### ISSUE TITLE
Better namespace?

### ISSUE THREAD

**Issue by Myslik** [Myslik/csharp-ember-handlebars#13]
Hello all,
I am wondering if current namspace `Ember.Handlebars` is the good one. Shouldn't we move it to `System.Web.Optimization` with rest of the Bundle Transforms?

I know it is a breaking change, but I suppose it would make more sense that way.
Let me know what you think.

**Comment by MilkyWayJoe** [comment]
I haven't thought about it to be quite honest, but I think the only argument I have is that the library should have its own, distinct, separate namespace instead of being appended to Microsoft's namespace. But I have no problem with the change. 

Perhaps it should be under `Myslik.Optimizations` instead? :smile: 

To put in perspective: JSON.NET uses `Newtonsoft` namespace, which was chosen after the creator's name

**Comment by Myslik** [comment]
Fair enough. I will probably let it be for now :smile:
