### ISSUE TITLE
{{partial}} naming issue

### ISSUE THREAD

**Issue by Globegitter** [Myslik/csharp-ember-handlebars#9]
When I try to render a partial, e.g. {{partial "test"}} I get this error: 
DEPRECATION: You tried to render the partial test, which should be at '_test', but Ember found 'test'. Please use a leading underscore in your partials
Even if I name the hbs file _test or add <script data-template-name="_test" type="text/x-handlebars-template">
Any idea why this could be?

**Comment by Myslik** [comment]
Do you have a snippet of code on which I could reproduce?

**Comment by Globegitter** [comment]
Will try to do that as soon as possible. Thanks for the update btw, really appreciated.

**Comment by MilkyWayJoe** [comment]
@Myslik perhaps we could add a few formatting idiom for templates following Ember's naming conventions. since we can't name the template files as `resourceName/templateName`, I'm (locally) using dash as replacement for slash and the transformer class eventually does the replace. We will eventually fall into scenarios that we need a partial under a specific resource (e.g. `product/_formView`) and we can't really do that as is.

I would suggest:
- `-` gets replaced with `/`. Example: `product_-formView.hbs` becomes `product/_formView` after compile
- `_` should not be replaced

**Comment by Myslik** [comment]
@MilkyWayJoe that is exactly what I am trying to solve right now. I have a working prototype that is trying to solve same issue as follows.
- `product/default.hbs` becomes `product`
- `product/_formView.hbs` becomes `product/_formView`

What do you think about that?

**Comment by MilkyWayJoe** [comment]
So you're reading the directories these files are and building the name from that?

If that's the case I think I understand, and it makes more sense to create templates per resource. So shared templates would be on the root of the templates directory, correct?

If this is not directory based, I would say we should go for a naming convention that translates to ember naming conventions as I said on the earlier comment.

Could you create a new branch in github with this code? I'm trying to fix another issue I have encountered with .Net resources out of sync with the new templates introduced in VS update. Maybe we could work to fix both issues on that branch and merge to master later.

Also, did you purposely wrote `product/default.hbs` or did you mean `product/index.hbs`? As per [conventions](http://emberjs.com/guides/routing/defining-your-routes/#toc_defining-your-routes) every `resource` has an `index` route.

**Comment by Myslik** [comment]
I will explain it a bit further. As I am developing a big project I wanted to better organize all Ember.js files. I have come up with something like this https://github.com/Myslik/csharp-ember-handlebars/wiki/Ember.js-Directory-Structure. So far I like this concept very much. I have all files needed for the route in one folder and the folder structure mirrors the router nicely. I purposely wrote `product/default.hbs` because that is the one that gets translated to `product`. If you need `index` template you can create one of these `product/index/default.hbs` or just `product/index.hbs`.

**Comment by MilkyWayJoe** [comment]
I'm afraid this is not the conventional way. I'm saying this because this library will be used by other people, including me, who are following all Ember conventions. Things like `default` template don't really exist in Ember and the framework don't respond to this template name, but by default it not only responds, but expects an `index` template for `resources`.

I'm not sure I understand everything about the file structure (and if I don't, I'm sorry). I'd really like to see it in the file structure and would be great if you could have a 2nd branch for it and other bugfixes. As per your wiki, the template files would be under the `routes` directory? If that's the case, it would different from what most people in the community use, and might create a different development path that applies only to .NET, which, I think, would be unfortunate as we would be doing it different from what is intended and from what majority of people do. I see problems in this approach for being unique; this would mean a person building a project in .NET, when facing issues/difficulties would not be able to find help from the community as a whole, but rather only from people supporting this specific library with a different structure.

I would advise to be consistent with the framework conventions for naming and for directory structure. And again, please create a 2nd branch. There is one issue that people are facing with incompatibility that I really would like to fix ASAP, but I have to talk and show you first; a 2nd branch would be ideal.

Please take a look into @trek's "yet another todo, done right" repo [here](https://github.com/trek/ember-todos-with-build-tools-tests-and-other-modern-conveniences/tree/master/app). This is almost exactly what I'm currently working with in terms of file structure and I would like to not get off from this structure.

**Comment by MilkyWayJoe** [comment]
@Myslik I was hoping for some feedback on this PR. We need it in NuGet as soon as you have time to, or let me know if you think anything else should be changed

**Comment by Myslik** [comment]
@MilkyWayJoe I have approved the PR and published NuGet. Sorry for the delay, but I was ill.

I would like to have a discussion about the directory structure of Ember.js project. I didn't know there is some convention already adopted by the community. I am working on rather big project build upon Ember and the problem is that in your example I would have a lot of files in one directory and no structure - seems messy. But I would rather stick to general convention then do it differently. Do you have more resources on the subject? I would love to learn more.

**Comment by MilkyWayJoe** [comment]
@Myslik created another ticket for this particular task. I like the solution you purpose (directories), but I'd like to talk more about it.

**Comment by uwo** [comment]
I'm curious what convention to use for naming and directory location with templates used in the {{render}} helper.  For example, suppose we want to `{{render "foo"}}`.   If the foo template is closely associated with a set of templates nested under the 'bar' directory, I would prefer to place it with them. But that will change the name of the foo template to 'bar/foo', which the {{render}} helper won't find.  For the time being, I am putting foo.hbs in the root of the Templates directory.  Anyone know a better solution?

Update: I've realized the error of my ways.  The solution for me was just to `{{render "bar/foo"}} and rename my controller to BarFooController.  Sorry to clutter up the response stream!
